### ISSUE TITLE
"What was your name again?"

### ISSUE THREAD

**Issue by clayote** [elseheartbreak/elseheartbreak.github.io#1]
I met Pixie at Club Yvonne, but didn't ask her name there. Then I had the dream about her, where I got her name, but didn't understand that the person in the dream was the same one I'd met in Club Yvonne.

That's not the game's fault. I'm quite bad at remembering how people look. In real life I end up asking people's names when I've seen them every day for months. But because I'd already had the initial conversation with her, there was no longer any way to ask her name. I spent several hours looking for Pixie without realizing I'd already found her.

I'd like some way of finding out a character's name again after I've been told it once. I don't think I should have to hack anything or restart the game for this.

My preferred solution would be to change the tooltip "talk to person" into "talk to Pixie" or whatever the NPC's name is, once Sebastian learns it.

**Comment by eriksvedang** [comment]
Yeah, that's an interesting idea. Let's try it!

**Comment by clayote** [comment]
:D

**Comment by clayote** [comment]
I guess this got fixed in 1.0.7. Thanks a bunch!
